project:
  type: website

website:
  site-url: https://berkeley-scf.github.io/compute-skills-2024
  sidebar:
    style: docked
    title: "Computational Skills Workshop"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-scf/compute-skills-2024
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Overview
      - href: prep.qmd
        text: Computational Environment
      - section: "Modules"
        contents:
          - href: units/comp-practices.qmd
            text: Computational Tools and Practices
          - href: units/additional-topics.qmd
            text: Numerics and Reproducibility
          - href: units/intro-computing.qmd
            text: Intro to Computing and Command Line (optional)
          - href: units/intro-python.qmd
            text: Intro to Python (optional)
          - href: units/mini-project.qmd
            text: Python Mini Project (optional)
      - href: license.qmd
        text: License
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



